name: tests

on: [push]
env:
  PYTHON_VERSION: 3.6

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python ${{env.PYTHON_VERSION}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{env.PYTHON_VERSION}}
    - name: Set up miniconda
      uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        auto-activate-base: true
        python-version: ${{env.PYTHON_VERSION}}
    - name: Set up the conda environment
      shell: bash -l {0}
      run: |
        conda env create --file src/environment.yml
    - name: Run integration tests
      shell: bash -l {0}
      run: |
        conda activate snakemake-pytest
        bash ci/check.sh
